-- 2026-06-13 init
create type user_role as enum ('student','tutor','admin');

create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  role user_role not null default 'student',
  full_name text,
  institution text,
  created_at timestamptz not null default now()
);

create table if not exists public.etudes (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  summary text,
  body_md text,
  metadata jsonb not null default '{}'::jsonb,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  etude_id bigint not null references public.etudes(id) on delete cascade,
  status text not null default 'not_started',
  updated_at timestamptz not null default now(),
  unique(user_id, etude_id)
);

create table if not exists public.ai_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  etude_id bigint references public.etudes(id) on delete set null,
  messages jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.etudes enable row level security;
alter table public.user_progress enable row level security;
alter table public.ai_sessions enable row level security;

create policy "etudes_read_published" on public.etudes for select using (published = true);
create policy "progress_read_own" on public.user_progress for select using (auth.uid() = user_id);
create policy "progress_write_own" on public.user_progress for insert with check (auth.uid() = user_id);
